/** Declaration file generated by dts-gen */

export function executeDataSet(config: any): any;

export function getDataSetList(config: any): any;

export function getDocumentHtml(config: any): any;

export function getQbeHtml(config: any): any;

export function getWorksheetHtml(config: any): any;

export function injectDocument(config: any): any;

export function injectQbe(config: any): any;

export function injectWorksheet(config: any): any;

export function setBaseUrl(config: any): void;

export namespace executeDataSet {
    const prototype: {
    };

}

export namespace getDataSetList {
    const prototype: {
    };

}

export namespace getDocumentHtml {
    const prototype: {
    };

}

export namespace getQbeHtml {
    const prototype: {
    };

}

export namespace getWorksheetHtml {
    const prototype: {
    };

}

export namespace injectDocument {
    const prototype: {
    };

}

export namespace injectQbe {
    const prototype: {
    };

}

export namespace injectWorksheet {
    const prototype: {
    };

}

export namespace setBaseUrl {
    const prototype: {
    };

}

