/** Declaration file generated by dts-gen */

export class Sbi {
    constructor(configModule: any);

    getDocumentHtml(documentHtmlConfigModule: any): any;

}

export namespace Sbi {
    namespace prototype {
        function getDocumentHtml(documentHtmlConfigModule: any): any;

        namespace getDocumentHtml {
            const prototype: {
            };

        }

    }

}

